"""Deterministic AWG 3.1 server and client configuration rendering."""

from __future__ import annotations

import ipaddress

from fluxgate.core.config import AmneziaWGConfig
from fluxgate.core.errors import ProviderError
from fluxgate.core.models import Client
from fluxgate.providers.amneziawg.models import AmneziaWGParameters, ResilienceProfile
from fluxgate.providers.wireguard.family import allocate_ipv4_address, validate_credential


def tunnel_network(settings: AmneziaWGConfig) -> ipaddress.IPv4Network:
    interface = ipaddress.ip_interface(settings.address)
    if interface.version != 4:
        raise ProviderError("AmneziaWG v0.5 requires an IPv4 tunnel network")
    return interface.network


def credential(
    client: Client, network: ipaddress.IPv4Network, profile: ResilienceProfile
) -> dict[str, object]:
    return validate_credential(
        client,
        network,
        provider="amneziawg",
        expected_profile_id=str(profile.id),
    )


def allocate_address(
    settings: AmneziaWGConfig, clients: list[Client], profile: ResilienceProfile
) -> str:
    interface = ipaddress.ip_interface(settings.address)
    if not isinstance(interface, ipaddress.IPv4Interface):
        raise ProviderError("AmneziaWG v0.5 requires an IPv4 tunnel network")
    return allocate_ipv4_address(
        interface.network,
        interface.ip,
        clients,
        provider="amneziawg",
        expected_profile_id=str(profile.id),
    )


def _parameter_lines(parameters: AmneziaWGParameters) -> list[str]:
    return [
        f"Jc = {parameters.jc}",
        f"Jmin = {parameters.jmin}",
        f"Jmax = {parameters.jmax}",
        f"S1 = {parameters.s1}",
        f"S2 = {parameters.s2}",
        f"H1 = {parameters.h1}",
        f"H2 = {parameters.h2}",
        f"H3 = {parameters.h3}",
        f"H4 = {parameters.h4}",
    ]


def render_server(
    settings: AmneziaWGConfig,
    private_key: str,
    clients: list[Client],
    profile: ResilienceProfile,
    *,
    runtime: bool = False,
) -> bytes:
    network = tunnel_network(settings)
    lines = ["# Managed by FluxGate AmneziaWG 3.1; local edits may be replaced.", "[Interface]"]
    if not runtime:
        lines.append(f"Address = {settings.address}")
    lines.extend(
        [
            f"ListenPort = {settings.listen_port}",
            f"PrivateKey = {private_key}",
            *_parameter_lines(profile.parameters),
        ]
    )
    for client in sorted(clients, key=lambda item: str(item.id)):
        value = credential(client, network, profile)
        lines.extend(
            [
                "",
                f"# Client {client.name} ({client.id})",
                "[Peer]",
                f"PublicKey = {value['public_key']}",
                f"AllowedIPs = {value['address']}",
            ]
        )
    return ("\n".join(lines) + "\n").encode()


def render_client(
    settings: AmneziaWGConfig,
    domain: str,
    server_public_key: str,
    client: Client,
    private_key: str,
    profile: ResilienceProfile,
) -> str:
    if not domain:
        raise ProviderError("server.domain is required to export an AmneziaWG client")
    value = credential(client, tunnel_network(settings), profile)
    lines = [
        "# Generated by FluxGate for AmneziaWG 3.1",
        "[Interface]",
        f"PrivateKey = {private_key}",
        f"Address = {value['address']}",
        f"DNS = {', '.join(settings.client_dns)}",
        *_parameter_lines(profile.parameters),
        "",
        "[Peer]",
        f"PublicKey = {server_public_key}",
        f"Endpoint = {domain}:{settings.listen_port}",
        "AllowedIPs = 0.0.0.0/0, ::/0",
        "PersistentKeepalive = 25",
    ]
    return "\n".join(lines) + "\n"
