"""Pure WireGuard addressing, validation, and configuration rendering."""

import ipaddress

from fluxgate.core.config import WireGuardConfig
from fluxgate.core.errors import ProviderError
from fluxgate.core.models import Client


def tunnel_network(settings: WireGuardConfig) -> ipaddress.IPv4Network:
    interface = ipaddress.ip_interface(settings.address)
    if interface.version != 4:
        raise ProviderError("WireGuard 0.1 currently requires an IPv4 tunnel network")
    return interface.network


def credential(client: Client, network: ipaddress.IPv4Network) -> dict[str, object]:
    value = client.provider_credentials["wireguard"]
    if set(value) != {"public_key", "address"}:
        raise ProviderError(f"invalid WireGuard credentials for client {client.name}")
    public_key = value["public_key"]
    address = value["address"]
    if (
        not isinstance(public_key, str)
        or not public_key
        or len(public_key) > 128
        or any(character.isspace() for character in public_key)
        or not isinstance(address, str)
    ):
        raise ProviderError(f"invalid WireGuard credentials for client {client.name}")
    try:
        interface = ipaddress.ip_interface(address)
    except ValueError as error:
        raise ProviderError(f"invalid WireGuard address for client {client.name}") from error
    if interface.version != 4 or interface.network.prefixlen != 32 or interface.ip not in network:
        raise ProviderError(f"invalid WireGuard address for client {client.name}")
    return value


def render_server(settings: WireGuardConfig, private_key: str, clients: list[Client]) -> bytes:
    network = tunnel_network(settings)
    lines = [
        "# Managed by FluxGate; local edits may be replaced.",
        "[Interface]",
        f"Address = {settings.address}",
        f"ListenPort = {settings.listen_port}",
        f"PrivateKey = {private_key}",
    ]
    for client in sorted(clients, key=lambda item: str(item.id)):
        client_credential = credential(client, network)
        lines.extend(
            [
                "",
                f"# Client {client.name} ({client.id})",
                "[Peer]",
                f"PublicKey = {client_credential['public_key']}",
                f"AllowedIPs = {client_credential['address']}",
            ]
        )
    return ("\n".join(lines) + "\n").encode()


def allocate_address(settings: WireGuardConfig, clients: list[Client]) -> str:
    network = tunnel_network(settings)
    server = ipaddress.ip_interface(settings.address).ip
    allocated = {
        ipaddress.ip_interface(str(credential(client, network)["address"])).ip for client in clients
    }
    for address in network.hosts():
        if address != server and address not in allocated:
            return f"{address}/32"
    raise ProviderError(f"no available client addresses in {network}")


def render_client(
    settings: WireGuardConfig,
    domain: str,
    server_public_key: str,
    client: Client,
    private_key: str,
) -> str:
    if not domain:
        raise ProviderError("server.domain is required to export a WireGuard client")
    client_credential = credential(client, tunnel_network(settings))
    return (
        "# Generated by FluxGate\n"
        "[Interface]\n"
        f"PrivateKey = {private_key}\n"
        f"Address = {client_credential['address']}\n"
        f"DNS = {', '.join(settings.client_dns)}\n\n"
        "[Peer]\n"
        f"PublicKey = {server_public_key}\n"
        f"Endpoint = {domain}:{settings.listen_port}\n"
        "AllowedIPs = 0.0.0.0/0\n"
        "PersistentKeepalive = 25\n"
    )
